# Generated by Django 5.1 on 2024-08-26 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musician_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(max_length=15)),
                ('instrument_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='album_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30)),
                ('album_relese_date', models.DateTimeField(auto_now_add=True)),
                ('relations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicians_App.musician_model')),
            ],
        ),
    ]
