# Generated by Django 5.0.1 on 2024-10-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('document', models.CharField(max_length=30)),
                ('dc', models.TextField(max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='post/media/uploads')),
            ],
        ),
    ]
