# Generated by Django 5.0.1 on 2024-10-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='img',
        ),
        migrations.AddField(
            model_name='post_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads'),
        ),
    ]
