# Generated by Django 5.0.1 on 2024-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_d',
            fields=[
                ('idd', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=30)),
            ],
        ),
    ]
