# Generated by Django 5.0.1 on 2024-10-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_input_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='input_d',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
