# Generated by Django 5.0.1 on 2024-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_input_d_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_d',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post/media/uploads/'),
        ),
    ]
