# Generated by Django 5.0.1 on 2024-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module14App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
