# Generated by Django 5.0.1 on 2024-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module14App', '0002_remove_student_id_student_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_form',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=15)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
